### ISSUE TITLE
Any way to record all incoming and outgoing messages?

### ISSUE THREAD

**Issue by luizcarvalho** [hellostealth/stealth#109]
Hello friends,

Exist any way to record all incoming and outgoing messages?

Example if I need store messages for analysis like a chatbase.com  or botanalytics.co or to check if a message was read by user (I need store message before)

Thanks for help guys =)

**Comment by luizcarvalho** [comment]
Solving  overriding Stealth classes

**Comment by mgomes** [comment]
I was going to recommend going this route. There are certain usecases where we don't want this for privacy or compliance reasons.

**Comment by luizcarvalho** [comment]
Nice @mgomes thank you =D
