### ISSUE TITLE
The url verification is failing [Facebook]

### ISSUE THREAD

**Issue by YanCarlos** [hellostealth/stealth#137]
Someone added a line to validate the content type of facebook request but that's failing because the content type is null, it's generating an exception. 

code failing -> https://github.com/hellostealth/stealth/blob/4f7f8e995522231afc8275ccaf33e3ee6d10a1d5/lib/stealth/server.rb#L36

<img width="1248" alt="screen shot 2018-12-28 at 12 28 41 pm" src="https://user-images.githubusercontent.com/5903138/50523086-36148080-0a9c-11e9-8a1b-0a2a91d6b518.png">

**Comment by mgomes** [comment]
@YanCarlos thanks for reporting! Version `1.1.2` will be released soon and will contain a fix for this.
