### ISSUE TITLE
Add a new route to my bot

### ISSUE THREAD

**Issue by YanCarlos** [hellostealth/stealth#150]
Hello, i trying to add an end-point for an external application, so i need to create a new route, how can i do this? help me please.

Right now the project have a end-point for facebook request like this ->
`https://58cc7345c9.ngrok.io/incoming/facebook`

I need to have something like this -> 
`https://58cc7345c9.ngrok.io/incoming/order`
or maybe ->
`https://58cc7345c9.ngrok.io/order`

Is that possible?

**Comment by mgomes** [comment]
@YanCarlos currently Stealth uses embedded Sinatra to ingest webhooks. You could overwrite `Stealth::Server` locally and add your own route that way. It's a little bit hacky.

A less hacky approach would be to write your own Stealth driver. Say you called it `order`, it would allow you handle all incoming requests to `/incoming/order` that way and process them however you  wish. I recommend taking a look at https://github.com/hellostealth/stealth-twilio as it's one of the more simpler integrations. Unfortunately writing a Stealth driver isn't documented at the moment.

**Comment by YanCarlos** [comment]
@mgomes thank you
