### ISSUE TITLE
Add support for custom reply sources

### ISSUE THREAD

**Issue by mgomes** [hellostealth/stealth#153]
Currently, `send_replies` will look for replies in the `replies/<flow_name>` directory. It should be extended to offer two additional options: `reply` and `inline`.

## Reply

In the case where we want to render a reply from a different directory than the default, the `reply` option  can be used. For example:

```ruby
send_replies reply: "some_other_folder/my_custom_reply"
```

This should still respect variant extensions.

## Inline

In the case where we have a reply loaded into memory, like if it was loaded from a database, we use the `inline` option:

```ruby
send_replies inline: my_reply_var
```

**Comment by luizcarvalho** [comment]
My friend @mgomes !!! I waited for this for a long time!!!
Thanks for this feature!!!

**Comment by mgomes** [comment]
Fixed in master.

**Comment by luizcarvalho** [comment]
Awesome!!!!
