### ISSUE TITLE
Try X times or step_to

### ISSUE THREAD

**Issue by Quintasan** [hellostealth/stealth#159]
I'm trying to build a reservation bot for Facebook Messenger and `Date.parse(current_message&.message)` can raise `ArgumentError` but it would be annoying for the user to get a catch_all after failing once and it would be annoying to ask him for a Date infinitely.

IMO it would be nice to have a helper that tries a given block X times and steps_to a given flow if it has tried X times.

What do you think?

**Comment by mgomes** [comment]
I haven't been able to think of a good way to handle this. Punting for now since this issue is stale.
