### ISSUE TITLE
Current session keys are not respecting session_ttl 

### ISSUE THREAD

**Issue by bhtabor** [hellostealth/stealth#189]
Current session keys are not respecting session ttl configured in environment.rb as below.

```
Stealth.config.session_ttl = ENV.fetch('STEALTH_SESSION_TTL', 0).to_i
```

Perhaps it is related to issue https://github.com/hellostealth/stealth/issues/160

**Comment by bhtabor** [comment]
Thank you very much @mgomes! We look forward to Stealth 2.0. Do you plan to also include a params hash to session as in https://github.com/hellostealth/stealth/pull/183? We've found it to be very useful.

**Comment by mgomes** [comment]
Fixed in master.
