### ISSUE TITLE
Incorrect Procfile in documentation

### ISSUE THREAD

**Issue by scotteknight** [hellostealth/stealth#192]
The documentation for deploying to Heroku [here](https://hellostealth.org/docs/#deployment) shows an out of date Procfile example. The correct Procfile should be:
```
web: bundle exec puma -C config/puma.rb
sidekiq: bundle exec sidekiq -C config/sidekiq.yml -q stealth_webhooks -q stealth_replies -r ./config/boot.rb

```
This is one of the breaking changes for version 1.1.0

**Comment by mgomes** [comment]
Thanks for reporting @scotteknight :+1:
