### ISSUE TITLE
Provide CatchAllsController w/ access to reason that caused CatchAll to fire

### ISSUE THREAD

**Issue by mgomes** [hellostealth/stealth#197]
This will be broken down into two categories: `:unknown_message` and `:error`.

## Unknown Message

When a user types or speaks something the bot does not expect, the reason should be set to `:unknown_message` or an equivalent. The message should also be passed to the `CatchAllsController` for further processing by the developer.

## Error

In the case a `StandardError` is raised, the reason should be set to `:error` and the error itself should be passed to the `CatchAllsController` for further processing by the developer.

**Comment by luizcarvalho** [comment]
I will love this... I use a horrible workaround to this works hahahaha

Thanks =D
