### ISSUE TITLE
Error : Transmitting. Response: 400:

### ISSUE THREAD

**Issue by francelwebdev** [hellostealth/stealth#199]
Good evening,
please, I have this error with the framework.

18:52:51 sidekiq.1 | [session] User 2352609204855187: setting session to welcome->ask_example
18:52:51 sidekiq.1 | [facebook] Transmitting. Response: 400: {"error":{"message":"Invalid OAuth access token.","type":"OAuthException","code":190,"fbtrace_id":"ApJxXCVdUD83QKezexApPLy"}}
18:52:52 sidekiq.1 | [facebook] Transmitting. Response: 400: {"error":{"message":"Invalid OAuth access token.","type":"OAuthException","code":190,"fbtrace_id":"AbysPB151Ci53nyUmZORrZm"}}
18:52:54 sidekiq.1 | [facebook] Transmitting. Response: 400: {"error":{"message":"Invalid OAuth access token.","type":"OAuthException","code":190,"fbtrace_id":"ADmM1D54uLEKQtDZukzWlUk"}}
18:52:54 sidekiq.1 | 2019-09-22T17:52:54.755Z 5199 TID-gq0svzal7 Stealth::Services::HandleMessageJob JID-ef1921d5af3885b7bdd5ea38 INFO: done: 3.714 sec

help me please

**Comment by mgomes** [comment]
@francelwebdev it sounds like you have an issue with your FB credentials. Make sure you are following the README in the hellostealth/stealth-facebook repo to generate the tokens.
