### ISSUE TITLE
Can't seem to access the docs anymore

### ISSUE THREAD

**Issue by jshum** [hellostealth/stealth#205]
Is the docs link on the home page pointing to some internal site: https://www.notion.so/whoisblackops/Stealth-6b6e164381fe41cb9896cebf8302fa42

Because I get a message saying that I need to be a member of 'Mav' to access the info

Thanks! Great work

**Comment by mgomes** [comment]
Hey @jshum. Sorry about that, it seems like somewhere I left a link to the Notion docs. For the upcoming version 2.0 I have been experimenting with using a new site for docs. I don't quite think Notion will work out, though. I am going to try readme.io next.

Anyway, for 1.1 (the current stable release) docs, you can still find those here: https://hellostealth.org/docs/
