### ISSUE TITLE
Is it possible to mount a Stealth bot inside an existent Rails app?

### ISSUE THREAD

**Issue by brunofrank** [hellostealth/stealth#308]
Since we have to create a really simple chatbot that will grow in a near future, I would like to know if is it possible to mount a Steal bot inside an existent Rails app, like an engine, or something like that?

Thank you!

**Comment by mgomes** [comment]
@brunofrank I don't think so. Though I am not an expert in engines. One thing we've found useful is to share a database in the beginning.

**Comment by luizcarvalho** [comment]
@mgomes and @brunofrank in my last project I did exactly this.  Two applications with shared databases.
