### ISSUE TITLE
Enable hot code reloading in development mode

### ISSUE THREAD

**Issue by mgomes** [hellostealth/stealth#55]
Since we already require `ActiveSupport`, the ideal implementation for this would mimic what is done by Rails via http://api.rubyonrails.org/classes/ActiveSupport/Reloader.html. That has the advantage of working on Mac, Linux, and Windows as well as only reloading files that have changed. I've looked at gems like `shotgun`, but the Rails implementation of this seems to be the most robust.

**Comment by iamjbecker** [comment]
Is anyone working on this yet?

**Comment by mgomes** [comment]
I have this a stab for v1.0, but I had a hard time getting it to work.

I attempted using the same style of reloading Rails uses since we already include ActiveSupport.

Help on this issue would be very appreciated. 🙏🏻

**Comment by iamjbecker** [comment]
Is it in a branch somewhere? I'm not sure where I'd start so I'd love to look at what there is. Happy to try and help along the way.

Just beginning my transition from just using Rails to actually learning Ruby ;) haha!

**Comment by mgomes** [comment]
Here's where I ended up: https://github.com/hellostealth/stealth/tree/reloader

Not much luck though 😞
