### ISSUE TITLE
Add support for service variants

### ISSUE THREAD

**Issue by mgomes** [hellostealth/stealth#56]
The bot should be able to send service-based replies. For example, if the bot is replying to a message via a state called `hello`:

Facebook users would receive the reply in `hello.yml+facebook.erb`
Twilio SMS users would receive the reply in `hello.yml+twilio.erb`
Every other service would receive the reply in `hello.yml.erb`

**Comment by narender2031** [comment]
can bot send the 1st message when session is create 1st time.

**Comment by luizcarvalho** [comment]
Wow this is a great feature. =)
