### ISSUE TITLE
Add support for broadcasts

### ISSUE THREAD

**Issue by mgomes** [hellostealth/stealth#57]
A bot should be able to move a user into any state, thereby sending them out-of-context messages.

**Comment by narender2031** [comment]
i would like to solve this. If you explain me more about this about this.

**Comment by mgomes** [comment]
I am open to suggestions here. Ultimately I think it should act similarly to `step_to_in` or `step_to_at` where it moves users to a new flow and state. I'm just not sure what the interface should look like.

Maybe it takes an array of user IDs, a `flow->state` string, and a `DateTime`?

**Comment by mgomes** [comment]
Closing this since I don't see a clear path forward. Happy to open this back up if it makes sense to handle broadcasts at the Stealth level.

**Comment by luizcarvalho** [comment]
☹️
