### ISSUE TITLE
uninitialized constant BotRecord (NameError)

### ISSUE THREAD

**Issue by b4thestorm** [hellostealth/stealth#72]
**Describe the bug**
Can not run stealth console in terminal. 

**To Reproduce**
1. open new terminal tab while in stealth generated app, invoke stealth console

**Expected behavior**
I expect after invoking stealth console in the terminal. I expect that a console prompt 
for stealth will show. 

**Screenshots**
<img width="1121" alt="screen shot 2018-06-03 at 5 43 19 pm" src="https://user-images.githubusercontent.com/4723872/40891563-af5accc8-6755-11e8-802b-9cc32e2c5bf7.png">

Instead of a prompt, there is a stack trace that says that BotRecord is uninitialized. 
However, there is a BotRecord file in the Bot/Models folder and my stealth generated flow named: Appointment Inherits from it.  

**Desktop (please complete the following information):**
 - OS: OS Mac Os 10.9.5
 - Browser:  Chrome 67.0.3396

**Additional context**

**Comment by mgomes** [comment]
This is due to your model beginning with the letter `A` being loaded before `BotRecord`. Will fix in `1.0.2`. Thanks for reporting!

**Comment by mgomes** [comment]
Fixed in 1.0.2.
