### ISSUE TITLE
How can I use typing indicator to slow tasks?

### ISSUE THREAD

**Issue by luizcarvalho** [hellostealth/stealth#78]
Hello awesome Stealth Team, I'm using Stealth to make a chatbot to get information from a internal API.

How can I **enable typing indicator** before a slow task, send replies with results and after to **disable typing indicator**? Something like this:

```
    class HellosController < BotController
    
      def say_hello
        # enable_typing_indicator
        # Execute a expensive task
        send_replies
        # disable_typing_indicator
      end
    
    end
```

It's possible? make sense? another way?

**Comment by matthewblack** [comment]
Hey @luizcarvalho - This is for a Facebook Messenger bot correct?

**Comment by luizcarvalho** [comment]
Exactly @matthewblack

**Comment by matthewblack** [comment]
Cool. So for Facebook Messenger, typing indicators are built in at the [reply level](https://github.com/hellostealth/stealth-facebook#delay) using delays. 

So if you wanted a longer delay you could increase the delay, to something like 5 seconds in your reply file, like such:

```
- reply_type: delay
  duration: 5
```

However, the best practice would always be to send expense tasks to a background job like Sidekiq. Which, is already built to the Stealth stack. :)
