### ISSUE TITLE
When exceptions happens, CatchAll->level1 is not called.

### ISSUE THREAD

**Issue by luizcarvalho** [hellostealth/stealth#80]
**Describe the bug**
If an exception occurs in my hellosController, for instance, the message `CatchAll level1 triggered for error` is showed, but leve1 action is never called. I investigate more deep and, for me, in [lib/stealth/controller/catch_all.rb:16](https://github.com/hellostealth/stealth/blob/master/lib/stealth/controller/catch_all.rb#L16) `CatchAllFlow` is not defined, and neve enter in `if condition`.

**To Reproduce**
1. Create a new project `stealth new teste `
2. Add gem 'stealth-facebook' and configure it.
3. Add a exception exemple in HellosController->say_hello, like a `1/0`
```
class HellosController < BotController
  def say_hello
    1/0
    send_replies
  end
end
```
4. Send a simple message on Messenger
5. Is showed 
`[catch_all] CatchAll level1 triggered for error-1540684789327149-hello-say_hello: divided by 0`
But level1 action is never called.

**Expected behavior**
CatchAll->level1 action should be called?

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome

**Additional context**

The FlowMap generated

```
class FlowMap

  include Stealth::Flow

  flow :hello do
    state :say_hello
  end

  flow :goodbye do
    state :say_goodbye
  end

  flow :catch_all do
    state :level1
  end

end

```

**Comment by mgomes** [comment]
What does your CatchAllsController look like?

**Comment by luizcarvalho** [comment]
Hello my friend @mgomes, is how it was generated

```
class CatchAllsController < BotController

  def level1
    send_replies

    if previous_session_specifies_fails_to?
      step_to flow: previous_session.flow_string, state: previous_state.to_s
    else
      step_to session: previous_session - 2.states
    end
  end

private
   def previous_session_specifies_fails_to?
     previous_state.present?
   end

   def previous_state
     previous_session.flow.current_state.fails_to
   end

end

```

**Comment by mgomes** [comment]
That's strange. It looks like the `level1` state was correctly called per your logs:

```
[catch_all] CatchAll level1 triggered
```

Do you have a reply defined for that state named `level.yml` in `replies/catch_alls`?. If so does it have any content?

**Comment by luizcarvalho** [comment]
I think the error is happens here, this message is showed, but condition is not satisfied. 

```
        def run_catch_all(reason: nil)
          error_level = fetch_error_level
          Stealth::Logger.l(topic: "catch_all", message: "CatchAll #{calculate_catch_all_state(error_level)} triggered for #{error_slug}: #{reason}")
          # THIS IF
          if defined?(CatchAllsController) && defined?(CatchAllFlow)
            catch_all_state = calculate_catch_all_state(error_level)

            if CatchAllFlow.flow_spec.states.keys.include?(catch_all_state.to_sym)
              step_to flow: 'catch_all', state: catch_all_state
            else
              # We are out of bounds, do nothing to prevent an infinite loop
              Stealth::Logger.l(topic: "catch_all", message: "Stopping; we've exceeded the number of defined catch_all states.")
              return false
            end
          end
        end

```
look:

08:42:19 sidekiq.1 | [3] pry(#<BotController>)> defined?(CatchAllsController)
08:42:19 sidekiq.1 | => "constant"
08:42:30 sidekiq.1 | [4] pry(#<BotController>)> defined?(CatchAllFlow)
08:42:30 sidekiq.1 | => nil
08:42:34 sidekiq.1 | [5] pry(#<BotController>)> CatchAllFlow
08:42:34 sidekiq.1 | NameError: uninitialized constant Stealth::Controller::CatchAll::CatchAllFlow
08:42:34 sidekiq.1 | from (pry):3:in `run_catch_all'

Here list of all defineds constants: https://gist.github.com/luizcarvalho/25b077521dcbb1e53949fbfd4d805180

**Comment by luizcarvalho** [comment]
You're welcome, thank you.
:smiley:
