### ISSUE TITLE
Rename current_user_id to current_session_id

### ISSUE THREAD

**Issue by itsjbecks** [hellostealth/stealth#91]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I'm currently using stealth as a micro service. In my main app, a User has multiple Encounters with the bot I'm building. I'm currently using the Encounter's ID as the session id within Stealth. This was done for quite a few reasons.

I feel that 'current_session_id' would provide more flexibility over 'current_user_id' to refer to the id of the current session. Curious about your guys' thoughts on this.

**Describe alternatives you've considered**
**Additional context**

**Comment by iamjbecker** [comment]
Clearly this is a super low priority, however, I wanted to start this conversation regardless.

**Comment by mgomes** [comment]
@itsjbecks This definitely makes sense. I don't recall why I named it `current_user_id` other than I think my mind was on `current_user`. I'll make `current_user_id` and `current_session_id` available starting with the upcoming 1.1 release. Then `current_user_id` can be deprecated later.

:+1:
